#import "imports.typ":*

#let hl = $frak(H)$
#let tl = $frak(T)$
= Star-Triangle Relation

There is another relation relating the partition functions of the honeycomb $hl$ and triangle $tl$ lattices. This is the star-triangle relation, by which we relate the Boltzmann weights of the star and triangle units. The honeycomb lattice $hl$ can be comprised of repeating star cells and the triangular lattice $tl$ can be comprised of repeating triangle cells[cf. @starrellab]. The triangle is obtained by summing over the red vertex $l$ in @starrellab, which is the vertex in the center of the star. 

#figure(
  image("assets/star_tri_rel.png", width: 50%),
  caption: [The triangular lattice generated by the star triangle relation from the honeycomb lattice.]
)<startridiag>

Note that the honeycomb lattice $hl$ is bipartite. The summand in @pfnhoney can be written as,
$
 product_l W(sigma_l|sigma_i, sigma_j, sigma_k) 
$<wformpfn>
where the product is over the red vertices $l$ in @startridiag and the Boltzmann weight $W$ is defined as,
$
  W(sigma_l|sigma_i, sigma_j, sigma_k) = exp[sigma_l (L_1 sigma_i + L_2 sigma_j + L_3 sigma_k)]
$
Let us denote the set of  black vertices by $A$ and the set of red vertices by $B$. Note during the summation written in  the form of @wformpfn, the spin $sigma_l$ appears in only one factor of the product.  We can then sum over the spins in the set $B$ to obtain the partition function as,
$
  Z_N^hl ({L}) = sum_(sigma in A) w(sigma_i,sigma_j,sigma_k)
$<pfnw>
where the Boltzmann weight $w$ is defined as,
$
  w(sigma_i,sigma_j,sigma_k) &= sum_(sigma_l in B) W(sigma_l|sigma_i, sigma_j, sigma_k)\
  &= 2 cosh(L_1 sigma_i + L_2 sigma_j + L_3 sigma_k)
$<boltzwform>
The sum in @pfnw is over the spins in the set $A$ which are the black vertices in @startridiag. $sigma_i, sigma_j, sigma_k$ are the spins in the three edges connected to the red vertex $l$ in each star in $hl$. Note from @boltzwform that $w(-sigma_i, -sigma_j, -sigma_k) = w(sigma_i, sigma_j, sigma_k)$. This means that there we can write $w(sigma_i, sigma_j, sigma_k)$ as,
$
  w(sigma_i, sigma_j, sigma_k) = R exp(K_1 sigma_j sigma_k + K_2 sigma_i sigma_k + K_3 sigma_i sigma_j)
$<startriweight>
where $R,K_1,K_2,K_3$ are found later, which causes this identity to hold true for all spins $sigma_i, sigma_j, sigma_k$. The partition function for $hl$ is then given by,
$
  Z_N^hl ({L}) = R^(N\/2) sum_(sigma in A) product_{i,j,k} exp(K_1 sigma_i sigma_j + K_2 sigma_i sigma_k + K_3 sigma_j sigma_k)
$
This is exactly the partition function for the triangular lattice $tl$ with $N\/2$ sites @pfntri. Then we can relate the partition function of $hl$ on $2N$ spins with the partition function of $tl$ on $N$ spins as,
$
  Z_(2N)^hl ({L}) = R^N Z_N^tl ({K})
$<strel>

This is known as the star triangle relation. The relation holds true for all spins $sigma_i, sigma_j, sigma_k$ and thus the Boltzmann weights $R,K_1,K_2,K_3$ are independent of the spins. 

#result("Star Triangle Relation")[
  The star triangle relation relates a honeycomb cell in $hl$ to a triangular cell in $tl$[cf. @starrellab]. There exists $R,K_1,K_2,K_3$ such the following relation holds true independent of the spins $sigma_i, sigma_j, sigma_k$,
$
 2 cosh(L_1 sigma_i + L_2 sigma_j + L_3 sigma_k) = R exp(K_1 sigma_i sigma_j + K_2 sigma_i sigma_k + K_3 sigma_j sigma_k)
$
]
See the next section (result) for the determination of the interaction coefficients $R,K_1,K_2,K_3$.
== Determination of Interaction coefficients
We now determine $R,K_1,K_2,K_3$ in @startriweight. Considering all cases in @boltzwform and @startriweight, we can write the following equations,
$
 2c_"  " &= 2 cosh(L_1 +L_2 + L_3) = R exp(K_1 + K_2 + K_3) \
 2c_1 &= 2 cosh(-L_1 +L_2 + L_3) = R exp(K_1 - K_2 - K_3) \
 2c_2 &= 2 cosh(L_1 -L_2 + L_3) = R exp(-K_1 + K_2 - K_3) \
 2c_3 &= 2 cosh(L_1 +L_2 - L_3) = R exp(-K_1 - K_2 + K_3) 
$<intstrel>
We can obtain $K_i$ just from these equations and some hyperbolic identities. Furthermore, we outline the procedure to obtain $K_1$ here, the others can be obtained similarly. 
$
  (c c_1)/(c_2 c_3) = exp(4 K_1)
$
We obtain,
$
  c_2 c_3 (exp(4K_1) - 1) &= cosh(L_1 + L_2 + L_3) cosh(-L_1 + L_2 + L_3) \
  & quad quad quad - cosh(L_1 + L_2 - L_3) cosh(L_1 - L_2 + L_3)\
  &= 4(sinh^2(L_2 + L_3) - sinh^2(L_2 - L_3))\
  &= sinh(2 L_2) sinh(2 L_3)
$
As a result of this we obtain,
$
sinh(2K_1) sinh(2 L_1) = (sinh(2 L_1) sinh(2 L_2) sinh(2 L_3))/(2 (c c_1 c_2 c_3)^(1\/2))
$<eq811>
Note that the @intstrel do not change if we permute the suffices $1,2,3$. The other two interaction coefficients $K_2, K_3$ can be obtained similarly, just by permuting the indices. The RHS of  @eq811 does not change if we permute the indices. Thus, we can write the following relation,
$
  sinh(2K_i) sinh(2 L_i) = k^(-1) quad quad quad i in {1,2,3}
$<eq812> 
This is a property of star triangle relations. The products $sinh(2K_i)sinh(2 L_i)$ are independent of the indices $i$. The coefficient $R$ is given as,
Using @intstrel @eq811 @eq812, we can write the following relation,
$
  R &= 2 k sinh(2 L_1) sinh(2 L_2) sinh(2 L_3) \
  &= 2/(k^2 sinh(2K_1) sinh(2K_2) sinh(2K_3)) 
$

#result("Star-Triangle Relation Partition Function")[
  
The star triangle relation relates the partition function of the honeycomb lattice $hl$ with $2N$ sites to the partition function of the triangular lattice $tl$ with $N$ sites. 
The relation is given by,
$
  Z_(2N)^hl ({L}) = R^N Z_N^tl ({K})
$
where the interaction coefficients $R,K_1,K_2,K_3$ are given by,
$
  R &= 2/(k^2 sinh(2K_1) sinh(2K_2) sinh(2K_3)) \
  sinh(2K_i) sinh(2 L_i) &= k^(-1) quad "for" i in {1,2,3}
$
and where 
$
(sinh(2 L_1) sinh(2 L_2) sinh(2 L_3))/(2 (c c_1 c_2 c_3)^(1\/2))
$
The value of $k$ can also be written in terms of ${K}$ as,
$
  k = ((1-v_1^2)(1-v_2^2)(1-v_3^2))/(4[(1+v_1 v_2 v_3)(v_1 + v_2 v_3)(  v_2 + v_1 v_3)(v_3 + v_1 v_2)]^(1\/2))
$
]

We will be using these relations show some commuting properties of the transfer matrices of the 2D Ising Model. Onsager mentioned this in his paper @Onsager1944, and later on in an article in @mills1971. In his words, the whole solution of the 2D Ising Model derived below was something he tried to solve for some "variety" after working on 2D Ising model. He mentions that if the square lattice is constructed diagonally, the diagonal transfer matrices commute.

This star triangle relation is derived in this section can also be used to locate the critical points of the Ising model on $hl$ and $tl$. This star triangle relation is also important in determining the critical point of the Ising model on $hl$ and $tl$. For more details on the criticality of $hl$ and $tl$, see @baxter1982.
